services:
  # Backend API Service
  - type: web
    name: studyspot-ai-backend
    env: node
    region: oregon
    plan: free
    rootDir: backend
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: API_VERSION
        value: v1
      - key: DATABASE_URL
        sync: false  # You'll manually add your existing database URL in Render dashboard
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_REFRESH_SECRET
        generateValue: true
      - key: JWT_EXPIRES_IN
        value: 7d
      - key: JWT_REFRESH_EXPIRES_IN
        value: 30d
      - key: FRONTEND_URL
        sync: false
      - key: ANTHROPIC_API_KEY
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_PUBLISHABLE_KEY
        sync: false
      - key: STRIPE_WEBHOOK_SECRET
        sync: false
      - key: STRIPE_BASIC_MONTHLY_PRICE_ID
        sync: false
      - key: STRIPE_BASIC_YEARLY_PRICE_ID
        sync: false
      - key: STRIPE_PREMIUM_MONTHLY_PRICE_ID
        sync: false
      - key: STRIPE_PREMIUM_YEARLY_PRICE_ID
        sync: false
      - key: AWS_ACCESS_KEY_ID
        sync: false
      - key: AWS_SECRET_ACCESS_KEY
        sync: false
      - key: AWS_REGION
        value: us-east-1
      - key: AWS_S3_BUCKET
        sync: false
    healthCheckPath: /health
    autoDeploy: true

  # Frontend Static Site
  - type: web
    name: studyspot-ai-frontend
    env: static
    region: oregon
    plan: free
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: VITE_API_URL
        sync: false
      - key: VITE_FIREBASE_API_KEY
        sync: false
      - key: VITE_FIREBASE_AUTH_DOMAIN
        sync: false
      - key: VITE_FIREBASE_PROJECT_ID
        sync: false
      - key: VITE_FIREBASE_STORAGE_BUCKET
        sync: false
      - key: VITE_FIREBASE_MESSAGING_SENDER_ID
        sync: false
      - key: VITE_FIREBASE_APP_ID
        sync: false
    autoDeploy: true

# Database Configuration
# Option 1: Create new database (uncomment if you want a separate database)
# databases:
#   - name: studyspot-learning-db
#     databaseName: studyspot_learning_production
#     plan: free
#     region: oregon

# Option 2: Use existing database (recommended if you already have one)
# You'll manually set DATABASE_URL in Render dashboard to point to your existing database
