services:
  # Backend API Service
  - type: web
    name: studyspot-ai-backend
    env: node
    region: oregon
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: API_VERSION
        value: v1
      - key: DATABASE_URL
        fromDatabase:
          name: studyspot-ai-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_REFRESH_SECRET
        generateValue: true
      - key: JWT_EXPIRES_IN
        value: 7d
      - key: JWT_REFRESH_EXPIRES_IN
        value: 30d
      - key: FRONTEND_URL
        sync: false
      - key: ANTHROPIC_API_KEY
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_PUBLISHABLE_KEY
        sync: false
      - key: STRIPE_WEBHOOK_SECRET
        sync: false
      - key: STRIPE_BASIC_MONTHLY_PRICE_ID
        sync: false
      - key: STRIPE_BASIC_YEARLY_PRICE_ID
        sync: false
      - key: STRIPE_PREMIUM_MONTHLY_PRICE_ID
        sync: false
      - key: STRIPE_PREMIUM_YEARLY_PRICE_ID
        sync: false
      - key: AWS_ACCESS_KEY_ID
        sync: false
      - key: AWS_SECRET_ACCESS_KEY
        sync: false
      - key: AWS_REGION
        value: us-east-1
      - key: AWS_S3_BUCKET
        sync: false
    healthCheckPath: /health
    autoDeploy: true

databases:
  - name: studyspot-ai-db
    databaseName: studyspot_ai_production
    plan: free
    region: oregon
